# @package agent
_target_: agent.dsquare.D2Agent
name: dsquare
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
ensemble_size: 10
stddev_clip: 0.3
nstep: 3
batch_size: 1024
init_critic: true
update_encoder: ${update_encoder}
greedy_epsilon: 0.2
ucb: 2
noise_coe: 0
weight: true
weight_offline: false
weight_lo: 0.1
weight_up: 10